import type { ThemeConfig } from '../types/theme'

type PresetTheme = Omit<ThemeConfig, 'cafeId' | 'name' | 'assets'>

export const presets: Record<string, PresetTheme> = {
  warm: {
    preset: 'warm',
    colors: {
      background: '#1a1008',
      surface: '#261a0e',
      surfaceHover: '#312010',
      primary: '#d4843a',
      primaryText: '#1a1008',
      textPrimary: '#f5e6d0',
      textSecondary: '#b89a78',
      textMuted: '#7a6050',
      border: '#3d2a18',
      cartBar: '#d4843a',
      cartBarText: '#1a1008',
      success: '#5a9e6f',
      error: '#c0554a',
    },
    typography: {
      fontDisplay: 'Playfair Display',
      fontBody: 'DM Sans',
      fontSizeBase: '16px',
      fontWeightDisplay: 700,
      fontWeightBody: 400,
      letterSpacingDisplay: '0.01em',
    },
    shape: {
      borderRadius: '12px',
      cardShadow: '0 4px 20px rgba(0,0,0,0.4)',
      imageBorderRadius: '8px',
    },
    layout: {
      headerStyle: 'branded',
      gridColumns: 2,
      showItemDescription: true,
      showCategoryIcons: false,
    },
  },

  modern: {
    preset: 'modern',
    colors: {
      background: '#fafafa',
      surface: '#ffffff',
      surfaceHover: '#f5f5f5',
      primary: '#111111',
      primaryText: '#ffffff',
      textPrimary: '#111111',
      textSecondary: '#555555',
      textMuted: '#aaaaaa',
      border: '#eeeeee',
      cartBar: '#111111',
      cartBarText: '#ffffff',
      success: '#2d8653',
      error: '#c0392b',
    },
    typography: {
      fontDisplay: 'Space Mono',
      fontBody: 'Inter',
      fontSizeBase: '15px',
      fontWeightDisplay: 700,
      fontWeightBody: 400,
      letterSpacingDisplay: '-0.02em',
    },
    shape: {
      borderRadius: '4px',
      cardShadow: '0 1px 3px rgba(0,0,0,0.08)',
      imageBorderRadius: '4px',
    },
    layout: {
      headerStyle: 'minimal',
      gridColumns: 1,
      showItemDescription: true,
      showCategoryIcons: true,
    },
  },

  minimal: {
    preset: 'minimal',
    colors: {
      background: '#ffffff',
      surface: '#ffffff',
      surfaceHover: '#f8f8f8',
      primary: '#333333',
      primaryText: '#ffffff',
      textPrimary: '#222222',
      textSecondary: '#666666',
      textMuted: '#bbbbbb',
      border: '#e8e8e8',
      cartBar: '#333333',
      cartBarText: '#ffffff',
      success: '#4caf50',
      error: '#e53935',
    },
    typography: {
      fontDisplay: 'DM Serif Display',
      fontBody: 'Inter',
      fontSizeBase: '16px',
      fontWeightDisplay: 400,
      fontWeightBody: 400,
      letterSpacingDisplay: '0em',
    },
    shape: {
      borderRadius: '8px',
      cardShadow: 'none',
      imageBorderRadius: '8px',
    },
    layout: {
      headerStyle: 'minimal',
      gridColumns: 2,
      showItemDescription: false,
      showCategoryIcons: false,
    },
  },

  luxury: {
    preset: 'luxury',
    colors: {
      background: '#0a0e1a',
      surface: '#12182b',
      surfaceHover: '#1a2040',
      primary: '#c9a84c',
      primaryText: '#0a0e1a',
      textPrimary: '#e8e0d0',
      textSecondary: '#9a8e7a',
      textMuted: '#5a5040',
      border: '#2a2a3a',
      cartBar: '#c9a84c',
      cartBarText: '#0a0e1a',
      success: '#5a9e6f',
      error: '#c0554a',
    },
    typography: {
      fontDisplay: 'Cormorant Garamond',
      fontBody: 'Inter',
      fontSizeBase: '16px',
      fontWeightDisplay: 600,
      fontWeightBody: 400,
      letterSpacingDisplay: '0.03em',
    },
    shape: {
      borderRadius: '2px',
      cardShadow: '0 8px 32px rgba(0,0,0,0.5)',
      imageBorderRadius: '2px',
    },
    layout: {
      headerStyle: 'fullImage',
      gridColumns: 1,
      showItemDescription: true,
      showCategoryIcons: false,
    },
  },
}
